Class {
	#name : 'CpIncludedChangedAnnouncement',
	#superclass : 'Announcement',
	#instVars : [
		'included'
	],
	#category : 'TripExpenses-UI-CodeParadise',
	#package : 'TripExpenses-UI-CodeParadise'
}

{ #category : 'accessing' }
CpIncludedChangedAnnouncement >> included [

	^ included
]

{ #category : 'accessing' }
CpIncludedChangedAnnouncement >> included: anObject [

	included := anObject
]
