Class {
	#name : 'CpWeightChangedAnnouncement',
	#superclass : 'Announcement',
	#instVars : [
		'weight'
	],
	#category : 'TripExpenses-UI-CodeParadise',
	#package : 'TripExpenses-UI-CodeParadise'
}

{ #category : 'accessing' }
CpWeightChangedAnnouncement >> weight [

	^ weight
]

{ #category : 'accessing' }
CpWeightChangedAnnouncement >> weight: anObject [

	weight := anObject
]
